### ISSUE TITLE
problem: executing emerald-rs throws a "cannot bind to socket error"

### ISSUE THREAD

**Issue by sjmackenzie** [ethereumproject/emerald-rs#6]
## Step to reproduce
1) `cd ~/.cargo/bin`
2) `./parity --chain dev --no-discovery --no-ui --no-ipc --no-dapps --rpccorsdomain "*" --jsonrpc-apis "web3,eth,net,personal,parity,parity_set,traces,rpc,parity_accounts"`
3) `./emerald-cli`

## Expected behaviour
`emerald-rs` should execute without error

## Actual behaivour
```
$  ~/.cargo/bin/emerald-cli 
thread '<unnamed>' panicked at 'Cannot bind to socket.: Error { repr: Os { code: 98, message: "Address already in use" } }', src/libcore/result.rs:837
stack backtrace:
   1:     0x55a00b04d0ba - std::sys::imp::backtrace::tracing::imp::write::ha21b0bc6fe1c6db2
   2:     0x55a00b04fddf - std::panicking::default_hook::{{closure}}::h9e3ab7c535ab99bb
   3:     0x55a00b04fab5 - std::panicking::default_hook::h8fcd4ede58ab2538
   4:     0x55a00b050277 - std::panicking::rust_panic_with_hook::he3e7d4fe905c61c0
   5:     0x55a00b050104 - std::panicking::begin_panic::ha3d6117597a7c9fd
   6:     0x55a00b050029 - std::panicking::begin_panic_fmt::hf9da00dc881251f3
   7:     0x55a00b04ffb7 - rust_begin_unwind
   8:     0x55a00b092d9d - core::panicking::panic_fmt::hfe9893b7b5c72fdb
   9:     0x55a00af803e0 - core::result::unwrap_failed::h145a54c9ba50c9aa
  10:     0x55a00af8cb34 - <jsonrpc_minihttp_server::ServerBuilder<M, S>>::start_http::{{closure}}::h1c64e6e592b63fe0
  11:     0x55a00af7b0e7 - std::panicking::try::do_call::h1e277e96adf245d0
  12:     0x55a00b0585f7 - __rust_maybe_catch_panic
  13:     0x55a00af85e84 - <F as alloc::boxed::FnBox<A>>::call_box::hb65e6a6ad669c014
  14:     0x55a00b052733 - std::sys::imp::thread::Thread::new::thread_start::h086b65e96d556e75
  15:     0x7f5427e181f3 - start_thread
  16:     0x7f542794512e - __GI___clone
  17:                0x0 - <unknown>
thread 'main' panicked at 'Unable to start RPC server: IoError(Error { repr: Custom(Custom { kind: Interrupted, error: StringError("") }) })', src/libcore/result.rs:837
stack backtrace:
   1:     0x55a00b04d0ba - std::sys::imp::backtrace::tracing::imp::write::ha21b0bc6fe1c6db2
   2:     0x55a00b04fddf - std::panicking::default_hook::{{closure}}::h9e3ab7c535ab99bb
   3:     0x55a00b04fab5 - std::panicking::default_hook::h8fcd4ede58ab2538
   4:     0x55a00b050277 - std::panicking::rust_panic_with_hook::he3e7d4fe905c61c0
   5:     0x55a00b050104 - std::panicking::begin_panic::ha3d6117597a7c9fd
   6:     0x55a00b050029 - std::panicking::begin_panic_fmt::hf9da00dc881251f3
   7:     0x55a00b04ffb7 - rust_begin_unwind
   8:     0x55a00b092d9d - core::panicking::panic_fmt::hfe9893b7b5c72fdb
   9:     0x55a00af80c6b - core::result::unwrap_failed::hdd37cf857fe541ac
  10:     0x55a00af99dbc - emerald_cli::start::h06ea2b352bb69f08
  11:     0x55a00af97976 - emerald_cli::main::h7bb1557bede898fe
  12:     0x55a00b0585f7 - __rust_maybe_catch_panic
  13:     0x55a00b052a2d - std::rt::lang_start::hc9ebe7230cf52cfd
  14:     0x7f542787d2df - __libc_start_main
  15:     0x55a00af6ad49 - _start
                        at ../sysdeps/x86_64/start.S:120
  16:                0x0 - <unknown>
```

**Comment by dulanov** [comment]
You need to set custom port for parity ` --jsonrpc-port "8546"`

**Comment by sjmackenzie** [comment]
```
$  ~/.cargo/bin/emerald-cli --jsonrpc-port "8546"
thread '<unnamed>' panicked at 'Cannot bind to socket.: Error { repr: Os { code: 98, message: "Address already in use" } }', src/libcore/result.rs:837
stack backtrace:
   1:     0x55f04ec990ba - std::sys::imp::backtrace::tracing::imp::write::ha21b0bc6fe1c6db2
   2:     0x55f04ec9bddf - std::panicking::default_hook::{{closure}}::h9e3ab7c535ab99bb
   3:     0x55f04ec9bab5 - std::panicking::default_hook::h8fcd4ede58ab2538
   4:     0x55f04ec9c277 - std::panicking::rust_panic_with_hook::he3e7d4fe905c61c0
   5:     0x55f04ec9c104 - std::panicking::begin_panic::ha3d6117597a7c9fd
   6:     0x55f04ec9c029 - std::panicking::begin_panic_fmt::hf9da00dc881251f3
   7:     0x55f04ec9bfb7 - rust_begin_unwind
   8:     0x55f04ecded9d - core::panicking::panic_fmt::hfe9893b7b5c72fdb
   9:     0x55f04ebcc3e0 - core::result::unwrap_failed::h145a54c9ba50c9aa
  10:     0x55f04ebd8b34 - <jsonrpc_minihttp_server::ServerBuilder<M, S>>::start_http::{{closure}}::h1c64e6e592b63fe0
  11:     0x55f04ebc70e7 - std::panicking::try::do_call::h1e277e96adf245d0
  12:     0x55f04eca45f7 - __rust_maybe_catch_panic
  13:     0x55f04ebd1e84 - <F as alloc::boxed::FnBox<A>>::call_box::hb65e6a6ad669c014
  14:     0x55f04ec9e733 - std::sys::imp::thread::Thread::new::thread_start::h086b65e96d556e75
  15:     0x7f4cd6a7a1f3 - start_thread
  16:     0x7f4cd65a712e - __GI___clone
  17:                0x0 - <unknown>
thread 'main' panicked at 'Unable to start RPC server: IoError(Error { repr: Custom(Custom { kind: Interrupted, error: StringError("") }) })', src/libcore/result.rs:837
stack backtrace:
   1:     0x55f04ec990ba - std::sys::imp::backtrace::tracing::imp::write::ha21b0bc6fe1c6db2
   2:     0x55f04ec9bddf - std::panicking::default_hook::{{closure}}::h9e3ab7c535ab99bb
   3:     0x55f04ec9bab5 - std::panicking::default_hook::h8fcd4ede58ab2538
   4:     0x55f04ec9c277 - std::panicking::rust_panic_with_hook::he3e7d4fe905c61c0
   5:     0x55f04ec9c104 - std::panicking::begin_panic::ha3d6117597a7c9fd
   6:     0x55f04ec9c029 - std::panicking::begin_panic_fmt::hf9da00dc881251f3
   7:     0x55f04ec9bfb7 - rust_begin_unwind
   8:     0x55f04ecded9d - core::panicking::panic_fmt::hfe9893b7b5c72fdb
   9:     0x55f04ebccc6b - core::result::unwrap_failed::hdd37cf857fe541ac
  10:     0x55f04ebe5dbc - emerald_cli::start::h06ea2b352bb69f08
  11:     0x55f04ebe3976 - emerald_cli::main::h7bb1557bede898fe
  12:     0x55f04eca45f7 - __rust_maybe_catch_panic
  13:     0x55f04ec9ea2d - std::rt::lang_start::hc9ebe7230cf52cfd
  14:     0x7f4cd64df2df - __libc_start_main
  15:     0x55f04ebb6d49 - _start
                        at ../sysdeps/x86_64/start.S:120
  16:                0x0 - <unknown>
```

**Comment by dulanov** [comment]
No, try with parity

**Comment by dulanov** [comment]
Sorry for that, instructions simply are not actual.

**Comment by sjmackenzie** [comment]
okay great, I'll make a PR
